name: smart_has
description: "Global Solution - Smart HAS"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase

  cloud_firestore: ^4.9.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  firebase_messaging: ^14.7.19

  # Gerenciamento de estado
  provider: ^6.1.2

  # Geolocalização e mapa
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # HTTP
  dio: ^5.4.3+1

  # Gráficos
  fl_chart: ^0.66.0

  # Armazenamento local
  shared_preferences: ^2.2.2

  # Abrir links externos
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
